name: Publish Packages to GitHub Packages

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0, v0.1.0)
  workflow_dispatch: # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for publishing to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@agent-system'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build --workspaces

      - name: Run tests
        run: npm test --workspaces
        env:
          # Skip integration tests in CI (they require API keys)
          CI: true

      - name: Publish @agent-system/core
        run: cd packages/core && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish @agent-system/cli
        run: cd packages/cli && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
